/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Modifica2.java
 *
 * Created on 04-jul-2013, 16:19:14
 */
package formularioderequerimientodeproductoservicio;

import Logica.ControladorLogica;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.ScrollPane;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Walter
 */
public class Modifica2 extends javax.swing.JFrame {

    /** Creates new form Modifica2 */
    
     private ControladorLogica cl;
    //private static ArrayList <HashMap>;
    private static DefaultTableModel ingresoDatos;
    private static String[] resultado= new String[7];
    private static String[] nombreTabla= {"Dtecnum1","Descripcion En detalle del Requerimiento","Producto/Servicio","Cantidad","Precio Estimado Unitario Neto","Valor Estimado Total por Item Neto","Valor total Pesos"};
    private static int valor=1;
    private static  HashMap <String, String[]> myMap = new HashMap<String, String[]>();
   
    
private static final long serialVersionUID = 1L;
private ScrollPane elSP;
    public Modifica2() {
       
        initComponents();
       PanelFondo F= new PanelFondo();
       this.add(F,BorderLayout.CENTER);
       this.pack();
       
       jLabel15.setText("Usuario en el sistema : "+Login.nom);
       
       cl= new ControladorLogica();     
       buttonGroup1.add(SeisDias);
       buttonGroup1.add(DiezDias);
       buttonGroup1.add(VeinteDias); 
       buttonGroup2.add(Producto);
       buttonGroup2.add(TrabajoSer);
       buttonGroup2.add(AsesoConsul);
       
       buttonGroup3.add(StockBodeSi);
       buttonGroup3.add(StockBodeNo);
       
       buttonGroup4.add(AnexoSi);
       buttonGroup4.add(AnexoNo);
       ingresoDatos = new DefaultTableModel(null, nombreTabla);
    
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        VBFinanzas = new javax.swing.JCheckBox();
        jLabel50 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Impuesto = new javax.swing.JTextField();
        ValorTPesos = new javax.swing.JTextField();
        VBAdquisiciones = new javax.swing.JCheckBox();
        ValEst = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        ItemAsignac = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        Saldo = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        AsigPptariaSubt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel30 = new javax.swing.JLabel();
        MotivosDelaNecesidadyDestino = new javax.swing.JTextField();
        RecomendaProve = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        ProBusOf = new javax.swing.JComboBox();
        MoDeRe = new javax.swing.JComboBox();
        jLabel35 = new javax.swing.JLabel();
        AnexoSi = new javax.swing.JRadioButton();
        AnexoNo = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        Dtecnum = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        FechaRecep = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Fecha1 = new javax.swing.JTextField();
        DeptoYUni = new javax.swing.JComboBox();
        Solicitante = new javax.swing.JTextField();
        Cargo = new javax.swing.JTextField();
        PeriUso = new javax.swing.JTextField();
        VeinteDias = new javax.swing.JRadioButton();
        SeisDias = new javax.swing.JRadioButton();
        DiezDias = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Recibe = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Producto = new javax.swing.JRadioButton();
        TrabajoSer = new javax.swing.JRadioButton();
        AsesoConsul = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        StockBodeSi = new javax.swing.JRadioButton();
        StockBodeNo = new javax.swing.JRadioButton();
        TipoCompra = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        HoraRecep = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        DescipGeneDelProSer = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        jLabel49.setText("Valor estimado (impto. Incl.)");
        jLabel49.setName("jLabel49"); // NOI18N

        jLabel14.setText("Valor de todo estimado en pesos");
        jLabel14.setName("jLabel14"); // NOI18N

        VBFinanzas.setName("VBFinanzas"); // NOI18N

        jLabel50.setText("$");
        jLabel50.setName("jLabel50"); // NOI18N

        jLabel1.setText("Impuesto");
        jLabel1.setName("jLabel1"); // NOI18N

        jButton1.setText("Guardar Formulario");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Impuesto.setName("Impuesto"); // NOI18N

        ValorTPesos.setName("ValorTPesos"); // NOI18N

        VBAdquisiciones.setName("VBAdquisiciones"); // NOI18N
        VBAdquisiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VBAdquisicionesActionPerformed(evt);
            }
        });

        ValEst.setName("ValEst"); // NOI18N

        jLabel44.setText("SUBT.");
        jLabel44.setName("jLabel44"); // NOI18N

        jLabel43.setText("Asig PPTARIA");
        jLabel43.setName("jLabel43"); // NOI18N

        ItemAsignac.setName("ItemAsignac"); // NOI18N

        jLabel46.setText("SALDO PPTARIO M$");
        jLabel46.setName("jLabel46"); // NOI18N

        jLabel48.setText("V° B° Adquisiciones");
        jLabel48.setName("jLabel48"); // NOI18N

        Saldo.setName("Saldo"); // NOI18N

        jLabel47.setText("V° B° finanzas");
        jLabel47.setName("jLabel47"); // NOI18N

        jLabel27.setText("Motivos de la necesidad y destino final del producto y/o servicio");
        jLabel27.setName("jLabel27"); // NOI18N

        jLabel45.setText("ITEM/ASIGNAC.");
        jLabel45.setName("jLabel45"); // NOI18N

        jLabel29.setText("Procedimientos de busqueda oferentes  (CM,LP,TD,<3UTM)");
        jLabel29.setName("jLabel29"); // NOI18N

        AsigPptariaSubt.setName("AsigPptariaSubt"); // NOI18N
        AsigPptariaSubt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsigPptariaSubtActionPerformed(evt);
            }
        });

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane2.setViewportView(jTable1);

        jLabel30.setText("Recomendacion de proveedores");
        jLabel30.setName("jLabel30"); // NOI18N

        MotivosDelaNecesidadyDestino.setName("MotivosDelaNecesidadyDestino"); // NOI18N

        RecomendaProve.setName("RecomendaProve"); // NOI18N
        RecomendaProve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecomendaProveActionPerformed(evt);
            }
        });

        jLabel31.setText("Motivo de recomendacion ( CM,TD,<3UTM)");
        jLabel31.setName("jLabel31"); // NOI18N

        ProBusOf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CM", "LP", "TD", "<3UTM" }));
        ProBusOf.setName("ProBusOf"); // NOI18N
        ProBusOf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProBusOfActionPerformed(evt);
            }
        });

        MoDeRe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CM", "TD", "<3UTM" }));
        MoDeRe.setName("MoDeRe"); // NOI18N

        jLabel35.setText("¿Anexo?");
        jLabel35.setName("jLabel35"); // NOI18N

        AnexoSi.setText("Si");
        AnexoSi.setName("AnexoSi"); // NOI18N

        AnexoNo.setText("No");
        AnexoNo.setName("AnexoNo"); // NOI18N

        jButton3.setText("Volver");
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Busqueda y despliegue");
        jToggleButton2.setName("jToggleButton2"); // NOI18N
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        Dtecnum.setName("Dtecnum"); // NOI18N
        Dtecnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DtecnumActionPerformed(evt);
            }
        });

        jLabel52.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel52.setText("Modificar Formulario De Requerimiento De Producto y/o Servicios");
        jLabel52.setName("jLabel52"); // NOI18N

        jLabel10.setText("Depto. y/o Unidad");
        jLabel10.setName("jLabel10"); // NOI18N

        FechaRecep.setName("FechaRecep"); // NOI18N

        jLabel3.setText("Fecha ");
        jLabel3.setName("jLabel3"); // NOI18N

        Fecha1.setName("Fecha1"); // NOI18N
        Fecha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fecha1ActionPerformed(evt);
            }
        });

        DeptoYUni.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Division Tecnica", "Unidad de Administración y Finanzas", "Unidad de Auditoría Interna", "Unidad de Ingeniería y Desarrollo", "Unidad de Operaciones" }));
        DeptoYUni.setName("DeptoYUni"); // NOI18N

        Solicitante.setName("Solicitante"); // NOI18N
        Solicitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolicitanteActionPerformed(evt);
            }
        });

        Cargo.setName("Cargo"); // NOI18N
        Cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargoActionPerformed(evt);
            }
        });

        PeriUso.setName("PeriUso"); // NOI18N
        PeriUso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PeriUsoActionPerformed(evt);
            }
        });

        VeinteDias.setText("+20 dias > 1000 utm");
        VeinteDias.setName("VeinteDias"); // NOI18N

        SeisDias.setText(" +6 dias < 100 utm");
        SeisDias.setName("SeisDias"); // NOI18N

        DiezDias.setText("+10 dias >100<1000 utm ");
        DiezDias.setName("DiezDias"); // NOI18N

        jLabel7.setText("Plazo publicacion solicitado ");
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel6.setText("2013  N° De Formulario :");
        jLabel6.setName("jLabel6"); // NOI18N

        Recibe.setName("Recibe"); // NOI18N

        jLabel5.setText("Recibe");
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel8.setText("Clase de Requerimiento");
        jLabel8.setName("jLabel8"); // NOI18N

        Producto.setText("Producto");
        Producto.setName("Producto"); // NOI18N

        TrabajoSer.setText("Trabajo/Servicio");
        TrabajoSer.setName("TrabajoSer"); // NOI18N

        AsesoConsul.setText("Asesoria/Consultoria");
        AsesoConsul.setName("AsesoConsul"); // NOI18N

        jLabel23.setText("Stock en Bodega");
        jLabel23.setName("jLabel23"); // NOI18N

        StockBodeSi.setText("Si");
        StockBodeSi.setName("StockBodeSi"); // NOI18N

        StockBodeNo.setText("No");
        StockBodeNo.setName("StockBodeNo"); // NOI18N

        TipoCompra.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rutinaria", "Estrategica" }));
        TipoCompra.setName("TipoCompra"); // NOI18N
        TipoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoCompraActionPerformed(evt);
            }
        });

        jLabel20.setText("Tipo De Compra");
        jLabel20.setName("jLabel20"); // NOI18N

        jLabel2.setText("Fechar recepcion para publicacion en marcadopublico.cl ");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel9.setText("Fecha");
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel12.setText("Cargo");
        jLabel12.setName("jLabel12"); // NOI18N

        jLabel11.setText("Solicitante");
        jLabel11.setName("jLabel11"); // NOI18N

        jLabel13.setText("Periodo de Uso");
        jLabel13.setName("jLabel13"); // NOI18N

        jLabel26.setText("Descripcion general de Producto / Servicio");
        jLabel26.setName("jLabel26"); // NOI18N

        HoraRecep.setName("HoraRecep"); // NOI18N

        jLabel4.setText("Hora");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel15.setName("jLabel15"); // NOI18N

        DescipGeneDelProSer.setName("DescipGeneDelProSer"); // NOI18N
        DescipGeneDelProSer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescipGeneDelProSerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel43)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AsigPptariaSubt, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ItemAsignac, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel45, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel46)
                            .addComponent(Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VBFinanzas)
                            .addComponent(jLabel47))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel48)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel50))
                            .addComponent(VBAdquisiciones))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ValEst, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                .addGap(3, 3, 3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel49)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ValorTPesos)
                                .addComponent(Impuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(185, 185, 185))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(537, 537, 537)
                        .addComponent(jLabel35)
                        .addGap(18, 18, 18)
                        .addComponent(AnexoSi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AnexoNo))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(163, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel31)
                                .addComponent(jLabel29))
                            .addGap(21, 21, 21))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel27)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addComponent(jLabel26)
                    .addComponent(jLabel30))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(MoDeRe, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ProBusOf, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(DescipGeneDelProSer, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RecomendaProve, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MotivosDelaNecesidadyDestino, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton3))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Fecha1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(14, 14, 14)
                                                    .addComponent(jLabel3))
                                                .addComponent(FechaRecep, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(24, 24, 24)
                                                    .addComponent(jLabel4))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(HoraRecep, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(24, 24, 24)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5)
                                                .addComponent(Recibe)))
                                        .addComponent(PeriUso)
                                        .addComponent(Cargo)
                                        .addComponent(Solicitante, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                        .addComponent(DeptoYUni, 0, 0, Short.MAX_VALUE)))
                                .addComponent(jLabel10))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel20)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(TipoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(DiezDias)
                                        .addComponent(SeisDias)
                                        .addComponent(VeinteDias))
                                    .addGap(21, 21, 21)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(AsesoConsul)
                                        .addComponent(Producto)
                                        .addComponent(TrabajoSer)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel23)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(StockBodeSi)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(StockBodeNo))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(32, 32, 32)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Dtecnum, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jToggleButton2)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(56, 56, 56)
                                    .addComponent(jLabel8)))))
                    .addContainerGap(163, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(304, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DescipGeneDelProSer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MotivosDelaNecesidadyDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MoDeRe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RecomendaProve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AnexoSi)
                            .addComponent(AnexoNo)
                            .addComponent(jLabel35))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProBusOf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ValorTPesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Impuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel45)
                            .addComponent(jLabel46)
                            .addComponent(jLabel47)
                            .addComponent(jLabel48)
                            .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel43)
                            .addComponent(jLabel50)
                            .addComponent(jLabel49))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ItemAsignac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AsigPptariaSubt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ValEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(VBAdquisiciones))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(VBFinanzas)))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel52)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton3))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(43, 43, 43)
                                    .addComponent(jLabel10)
                                    .addGap(14, 14, 14)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(DeptoYUni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(10, 10, 10)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Solicitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12))
                                    .addGap(16, 16, 16)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(PeriUso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel13)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(jToggleButton2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Dtecnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(SeisDias)
                                        .addComponent(Producto))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(DiezDias)
                                        .addComponent(TrabajoSer))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(25, 25, 25)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel20)
                                                .addComponent(TipoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel23)
                                                .addComponent(StockBodeSi)
                                                .addComponent(StockBodeNo)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(VeinteDias)
                                            .addComponent(AsesoConsul))))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(FechaRecep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HoraRecep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(Recibe))))
                    .addContainerGap(632, Short.MAX_VALUE)))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here
        boolean ingreso= true;
        String FechaRecp1=  FechaRecep.getText();
        String HoraRecep1= HoraRecep.getText();     
        boolean Recibe1= Recibe.isSelected();
        String Dtecnum1=  Dtecnum.getText();
        String Fecha =Fecha1.getText();
        String Solicitante1 = Solicitante.getText();
        String Cargo1 = Cargo.getText();
        String PeriUso1= PeriUso.getText();
        String Plazo="";
        if(SeisDias.isSelected()){
        Plazo="6";
        }
        if(DiezDias.isSelected()){
        Plazo="10";
        }
        if(VeinteDias.isSelected()){
        Plazo="20";
        }
        
        String Clase="";
        
        if(Producto.isSelected()){
        Clase="p";
        }
        if(TrabajoSer.isSelected()){
        Clase="ts";
        }
        if(AsesoConsul.isSelected()){
        Clase="ac";
        }
       
        String StockBode="";
       if(StockBodeSi.isSelected()){     
       StockBode="s";
       }
       if(StockBodeNo.isSelected()){
       StockBode="n";    
       }
       String DescipGeneDelProSer1=DescipGeneDelProSer.getText();
       String MotivosDelaNecesidadyDestino1=MotivosDelaNecesidadyDestino.getText();
       String RecomendaProve1= RecomendaProve.getText();
       String Anexo="";
       if(AnexoSi.isSelected()){     
       Anexo="s";
       }
       if(AnexoNo.isSelected()){
       Anexo="n";    
       }
        String AsigPptariaSubt1= AsigPptariaSubt.getText();
        String ItemAsignac1=ItemAsignac.getText();
        int Saldo1=0;
        try{
        Saldo1=Integer.parseInt(Saldo.getText());
        }catch(Exception e){
            
        JOptionPane.showMessageDialog(this, "Debe ingresar solo numeros en el saldo", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
        }
        boolean vbffinanzas= VBFinanzas.isSelected(); 
        boolean vbaadquisiciones= VBAdquisiciones.isSelected();   
        Object depu = DeptoYUni.getSelectedItem();
        String DepUni = String.valueOf(depu);
        Object e = TipoCompra.getSelectedItem();
        String TipoC = String.valueOf(e);
        Object eo = MoDeRe.getSelectedItem();
        String MoDeR = String.valueOf(eo);
        Object eoi = ProBusOf.getSelectedItem();
        String ProBusO = String.valueOf(eoi);
        double ValEst1=Double.parseDouble(ValEst.getText());  
        double Vtp= Double.parseDouble(ValorTPesos.getText());
        double Imp= Double.parseDouble(Impuesto.getText());
    if(Saldo1==0){
    JOptionPane.showMessageDialog(this, "Debe ingresar un numero en el saldo", "Advertencia", JOptionPane.OK_CANCEL_OPTION);      
    ingreso= false;
    }
    if(myMap==null){
    JOptionPane.showMessageDialog(this, "Debe ingresar algun producto o servicio a la lista", "Advertencia", JOptionPane.OK_CANCEL_OPTION);      
    ingreso= false;
    } 
    if(FechaRecep.getText().equals("")){
    JOptionPane.showMessageDialog(this, "Debe ingresar la fecha para publicacion en mercadolibre.cl", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
    FechaRecep.setBackground(Color.RED);
    ingreso= false;
    }
    if(HoraRecep.getText().equals("")){
    JOptionPane.showMessageDialog(this, "Debe ingresar la hora para la publicacion en mercadolibre.cl", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
    HoraRecep.setBackground(Color.RED);
    ingreso= false;
    }
    if(Dtecnum.getText().equals("")){
    JOptionPane.showMessageDialog(this, "Debe ingresar el Numero del formulario de requerimiento", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
    Dtecnum.setBackground(Color.RED);
    ingreso= false;
    }
    if(Fecha1.getText().equals("")){
    JOptionPane.showMessageDialog(this, "Debe ingresar la Fecha del formulario", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
    Fecha1.setBackground(Color.RED);
    ingreso= false;
    }  
    if(Solicitante.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Debe ingresar el solicitante", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
        Solicitante.setBackground(Color.RED);
        ingreso= false;
    }
    if(Cargo.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Debe ingresar el Cargo", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
        Cargo.setBackground(Color.RED);
        ingreso= false;
    }
    if(PeriUso.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Debe ingresar el Periodo de uso", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
        PeriUso.setBackground(Color.RED);
        ingreso= false;
    }
    if(DescipGeneDelProSer.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Debe ingresar la descripcion general del producto/servicio", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
        DescipGeneDelProSer.setBackground(Color.RED);
        ingreso= false;
    }
    if(MotivosDelaNecesidadyDestino.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Debe ingresar el motivo de necesidad y destino final del producto y/o servicio", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
        MotivosDelaNecesidadyDestino.setBackground(Color.RED);
        ingreso= false;
    }
    if(RecomendaProve.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Debe ingresar Recomendacion de proveedores", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
        RecomendaProve.setBackground(Color.RED);
        ingreso= false;
    }
    if(AsigPptariaSubt.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Debe ingresar la asignacion Pptaria subt", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
        AsigPptariaSubt.setBackground(Color.RED);
        ingreso= false;
    }
    if(ItemAsignac.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Debe ingresar la asignacion Pptaria Item/ Asignac.", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
        ItemAsignac.setBackground(Color.RED);
        ingreso= false;
    }    
     if(Saldo.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Debe ingresar la persona a cargo de la decision ", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
        Saldo.setBackground(Color.RED);
        ingreso= false;
    }
    if(ingreso){
       boolean resul=cl.Modificar1(FechaRecp1,HoraRecep1,Recibe1,Dtecnum1,Fecha,DepUni,Solicitante1,Cargo1,PeriUso1,Plazo,Clase,TipoC,StockBode,DescipGeneDelProSer1,MotivosDelaNecesidadyDestino1,ProBusO,RecomendaProve1,MoDeR,Anexo,AsigPptariaSubt1,ItemAsignac1,Saldo1,vbffinanzas,vbaadquisiciones,ValEst1,Vtp,Imp);
       //boolean result2=cl.AgregarListaDeDatos(myMap, Dtecnum.getText());     
       Mail m = new Mail("Se ha modificado un formulario de requerimiento. Numero de formulario : "+ Dtecnum.getText()+" Usuario que lo ingresó :"+ Login.nom);
       m.send();// Mandar mensaje de modificacion de archivo  " Se ha ingresado el formulario de requerimiento numero:....por la cuenta con nombre:" 
       if(resul){//&&resul
       JOptionPane.showMessageDialog(this, "Se ha ingresado el formulario junto con su lista de productos de forma exitosa", "Informacion", ICONIFIED);
       }else{
       JOptionPane.showMessageDialog(this, "No se ha logrado ingresar el formulario, revise los campos de datos", "Informacion", JOptionPane.OK_OPTION);
       myMap=null;
       resultado=null;
       valor=0;
       }
    }else{
        JOptionPane.showMessageDialog(this, "No se ha logrado ingresar, revise los campos de datos", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
    
    }   
}//GEN-LAST:event_jButton1ActionPerformed

private void VBAdquisicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VBAdquisicionesActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_VBAdquisicionesActionPerformed

private void AsigPptariaSubtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsigPptariaSubtActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_AsigPptariaSubtActionPerformed

private void RecomendaProveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecomendaProveActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_RecomendaProveActionPerformed

private void ProBusOfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProBusOfActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_ProBusOfActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
    new GestionMenu().setVisible(true);
    this.setVisible(false);
    
}//GEN-LAST:event_jButton3ActionPerformed

private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
         if(!Dtecnum.getText().equals("")){
        try{
        int Numero= Integer.parseInt(Dtecnum.getText());
        HashMap datos = cl.BuscarFormulario(Numero);          
        if(datos!=null){
        String FechaRecep1=(String)datos.get("FechaRecp1");
        System.out.println("este es el valor de fecha : "+FechaRecep1);
        FechaRecep.setText(FechaRecep1);
       
        String HoraRecep1=(String)datos.get("HoraRecep1");
        HoraRecep.setText(HoraRecep1);
        String Recibe1=(String)datos.get("Recibe");
        if(Recibe1.equals("1")){Recibe.setSelected(true);}else{Recibe.setSelected(false);}
        String Fecha11=(String)datos.get("Fecha"); 
        Fecha1.setText(Fecha11);
        String Deptoyounidad1=(String)datos.get("Deptoyounidad1");
        DeptoYUni.setSelectedItem(Deptoyounidad1);
        String TipoC=(String)datos.get("TC");
        TipoCompra.setSelectedItem(TipoC);
        String ProBF=(String)datos.get("ProcedDeBusqueda1");        
        ProBusOf.setSelectedItem(ProBF);
        String MDR=(String)datos.get("MotivoDeRecom1");
        MoDeRe.setSelectedItem(MDR);
        String Solicitante1=(String)datos.get("Solicitante1");
        Solicitante.setText(Solicitante1);
        String Cargo1=(String)datos.get("Cargo1");
        Cargo.setText(Cargo1);
        String PeriUso1=(String)datos.get("PeriUso1");
        PeriUso.setText(PeriUso1);
        String Plazo1=(String)datos.get("Plazo");
        String Clase1=(String)datos.get("Clase"); 
        String Stockbode1=(String)datos.get("StockBode");
        String Anexo1=(String)datos.get("Anexo"); 
        if(Plazo1.equals("6")){
        SeisDias.setSelected(true);
        }
        if(Plazo1.equals("10")){
        DiezDias.setSelected(true);
        }
        if(Plazo1.equals("20")){
        VeinteDias.setSelected(true);
        }
        if(Clase1.equals("p")){
        Producto.setSelected(true);
        }
        if(Clase1.equals("ts")){
        TrabajoSer.setSelected(true);
        }
        if(Clase1.equals("ac")){
        AsesoConsul.setSelected(true);
        }
        if(Stockbode1.equals("s")){     
        StockBodeSi.setSelected(true);
        }
        if(Stockbode1.equals("n")){
        StockBodeNo.setSelected(true);    
        }
        if(Stockbode1.equals("s")){     
        StockBodeSi.setSelected(true);
        }
        if(Stockbode1.equals("n")){
        StockBodeNo.setSelected(true);    
        }
        if(Anexo1.equals("s")){     
        AnexoSi.setSelected(true);
        }
        if(Anexo1.equals("n")){
        AnexoNo.setSelected(true);    
        }
        String DescipgeneDelProSer1=(String)datos.get("DescipGeneDelProSer1");
        DescipGeneDelProSer.setText(DescipgeneDelProSer1);
        String MotivosDelaNecesidadyDestino1=(String)datos.get("MotivosDelaNecesidadyDestino1");
        MotivosDelaNecesidadyDestino.setText(MotivosDelaNecesidadyDestino1);
        String RecomendaProve1=(String)datos.get("RecomendaProve1");
        RecomendaProve.setText(RecomendaProve1);
        String AsigPptariasubt1=(String)datos.get("AsigPptariaSubt1");
        AsigPptariaSubt.setText(AsigPptariasubt1);
        String ItemAsignac1=(String)datos.get("ItemAsignac1");
        ItemAsignac.setText(ItemAsignac1);
        String Saldo1=(String)datos.get("Saldo1");
        Saldo.setText(Saldo1);
        String vbffinanzas1=(String)datos.get("vbffinanzas");
        if(vbffinanzas1.equals("1")){VBFinanzas.setSelected(true); }else{VBFinanzas.setSelected(false);}
        String vbaadquisiciones1=(String)datos.get("vbaadquisiciones");
        if(vbaadquisiciones1.equals("1")){VBAdquisiciones.setSelected(true); }else{ VBAdquisiciones.setSelected(false);}        
        String ValEst1=(String)datos.get("ValEst1");
        ValorTPesos.setEditable(false);
        ValEst.setText(ValEst1);
        ValEst.setEditable(false);
        String Valtp=(String)datos.get("ValorTPesos");
        ValorTPesos.setText(Valtp);
        String impe=(String)datos.get("Impuesto");
        Impuesto.setText(impe);
        Impuesto.setEditable(false);
        jTable1.setModel(cl.cargarTablaDatoslo(Numero));    
        }else{
        JOptionPane.showMessageDialog(this, "Formulario no existente, vuelva a ingresar el numero", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
        }
            }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Debe ingresar solo numeros en el numero del formulario", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
            }
        
}else{
        JOptionPane.showMessageDialog(this, "Debe ingresar un numero de formulario", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
       
        Dtecnum.setBackground(Color.RED);

}
}//GEN-LAST:event_jToggleButton2ActionPerformed

private void DtecnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DtecnumActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_DtecnumActionPerformed

private void Fecha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fecha1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_Fecha1ActionPerformed

private void SolicitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolicitanteActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_SolicitanteActionPerformed

private void CargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargoActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_CargoActionPerformed

private void PeriUsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PeriUsoActionPerformed
// TODO add your handling code here:     
}//GEN-LAST:event_PeriUsoActionPerformed

private void TipoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoCompraActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_TipoCompraActionPerformed

private void DescipGeneDelProSerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescipGeneDelProSerActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_DescipGeneDelProSerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modifica2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modifica2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modifica2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modifica2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Modifica2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AnexoNo;
    private javax.swing.JRadioButton AnexoSi;
    private javax.swing.JRadioButton AsesoConsul;
    private javax.swing.JTextField AsigPptariaSubt;
    private javax.swing.JTextField Cargo;
    private javax.swing.JComboBox DeptoYUni;
    private javax.swing.JTextField DescipGeneDelProSer;
    private javax.swing.JRadioButton DiezDias;
    private javax.swing.JTextField Dtecnum;
    private javax.swing.JTextField Fecha1;
    private javax.swing.JTextField FechaRecep;
    private javax.swing.JTextField HoraRecep;
    private javax.swing.JTextField Impuesto;
    private javax.swing.JTextField ItemAsignac;
    private javax.swing.JComboBox MoDeRe;
    private javax.swing.JTextField MotivosDelaNecesidadyDestino;
    private javax.swing.JTextField PeriUso;
    private javax.swing.JComboBox ProBusOf;
    private javax.swing.JRadioButton Producto;
    private javax.swing.JCheckBox Recibe;
    private javax.swing.JTextField RecomendaProve;
    private javax.swing.JTextField Saldo;
    private javax.swing.JRadioButton SeisDias;
    private javax.swing.JTextField Solicitante;
    private javax.swing.JRadioButton StockBodeNo;
    private javax.swing.JRadioButton StockBodeSi;
    private javax.swing.JComboBox TipoCompra;
    private javax.swing.JRadioButton TrabajoSer;
    private javax.swing.JCheckBox VBAdquisiciones;
    private javax.swing.JCheckBox VBFinanzas;
    private javax.swing.JTextField ValEst;
    private javax.swing.JTextField ValorTPesos;
    private javax.swing.JRadioButton VeinteDias;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
