/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ulti.java
 *
 * Created on 16-jun-2013, 23:40:34
 */
package formularioderequerimientodeproductoservicio;

import Logica.ControladorLogica;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.ScrollPane;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Walter
 */
public class Modificar1 extends javax.swing.JFrame {
 private ControladorLogica cl;
    //private static ArrayList <HashMap>;
    private static DefaultTableModel ingresoDatos;
    private static String[] resultado= new String[7];
    private static String[] nombreTabla= {"Dtecnum1","Descripcion En detalle del Requerimiento","Producto/Servicio","Cantidad","Precio Estimado Unitario Neto","Valor Estimado Total por Item Neto","Valor total Pesos"};
    private static int valor=1;
    private static  HashMap <String, String[]> myMap = new HashMap<String, String[]>();
   
    
private static final long serialVersionUID = 1L;
private ScrollPane elSP;
   
    /** Creates new form ulti */
    public Modificar1() {
       initComponents();
       PanelFondo F= new PanelFondo();
       this.add(F,BorderLayout.CENTER);
       this.pack();
       
       jLabel15.setText("Usuario en el sistema : "+Login.nom);
       
       cl= new ControladorLogica();     
       buttonGroup1.add(SeisDias);
       buttonGroup1.add(DiezDias);
       buttonGroup1.add(VeinteDias); 
       buttonGroup2.add(Producto);
       buttonGroup2.add(TrabajoSer);
       buttonGroup2.add(AsesoConsul);
       
       buttonGroup3.add(StockBodeSi);
       buttonGroup3.add(StockBodeNo);
       
       buttonGroup4.add(AnexoSi);
       buttonGroup4.add(AnexoNo);
       ingresoDatos = new DefaultTableModel(null, nombreTabla);
    
        
    }

  
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PeriUso = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Fecha1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Cargo = new javax.swing.JTextField();
        Solicitante = new javax.swing.JTextField();
        Recibe = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        HoraRecep = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        FechaRecep = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        Dtecnum = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        DescipGeneDelProSer = new javax.swing.JTextField();
        MotivosDelaNecesidadyDestino = new javax.swing.JTextField();
        RecomendaProve = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        DiezDias = new javax.swing.JRadioButton();
        SeisDias = new javax.swing.JRadioButton();
        TrabajoSer = new javax.swing.JRadioButton();
        VeinteDias = new javax.swing.JRadioButton();
        TipoCompra = new javax.swing.JComboBox();
        Producto = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        AsesoConsul = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        StockBodeSi = new javax.swing.JRadioButton();
        StockBodeNo = new javax.swing.JRadioButton();
        jLabel35 = new javax.swing.JLabel();
        AnexoSi = new javax.swing.JRadioButton();
        AnexoNo = new javax.swing.JRadioButton();
        MoDeRe = new javax.swing.JComboBox();
        ProBusOf = new javax.swing.JComboBox();
        DeptoYUni = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ValorTPesos = new javax.swing.JTextField();
        Impuesto = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        VBFinanzas = new javax.swing.JCheckBox();
        VBAdquisiciones = new javax.swing.JCheckBox();
        ValEst = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        Saldo = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        ItemAsignac = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        AsigPptariaSubt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 30000));
        jPanel1.setPreferredSize(new java.awt.Dimension(1457, 800));

        jLabel6.setText("2013  N° De Formulario :");

        jLabel2.setText("Fechar recepcion para publicacion en marcadopublico.cl ");

        jLabel9.setText("Fecha");

        jLabel5.setText("Recibe");

        PeriUso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PeriUsoActionPerformed(evt);
            }
        });

        jLabel11.setText("Solicitante");

        Fecha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fecha1ActionPerformed(evt);
            }
        });

        jLabel12.setText("Cargo");

        jLabel10.setText("Depto. y/o Unidad");

        jLabel13.setText("Periodo de Uso");

        Cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargoActionPerformed(evt);
            }
        });

        Solicitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolicitanteActionPerformed(evt);
            }
        });

        jLabel3.setText("Fecha ");

        jLabel4.setText("Hora");

        jButton3.setText("Volver");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Dtecnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DtecnumActionPerformed(evt);
            }
        });

        jLabel52.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel52.setText("Modificar Formulario De Requerimiento De Producto y/o Servicios");

        jLabel31.setText("Motivo de recomendacion ( CM,TD,<3UTM)");

        DescipGeneDelProSer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescipGeneDelProSerActionPerformed(evt);
            }
        });

        RecomendaProve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecomendaProveActionPerformed(evt);
            }
        });

        jLabel26.setText("Descripcion general de Producto / Servicio");

        jLabel29.setText("Procedimientos de busqueda oferentes  (CM,LP,TD,<3UTM)");

        jLabel27.setText("Motivos de la necesidad y destino final del producto y/o servicio");

        jLabel30.setText("Recomendacion de proveedores");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jToggleButton2.setText("Busqueda y despliegue");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jLabel23.setText("Stock en Bodega");

        jLabel20.setText("Tipo De Compra");

        DiezDias.setText("+10 dias >100<1000 utm ");

        SeisDias.setText(" +6 dias < 100 utm");

        TrabajoSer.setText("Trabajo/Servicio");

        VeinteDias.setText("+20 dias > 1000 utm");

        TipoCompra.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rutinaria", "Estrategica" }));
        TipoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoCompraActionPerformed(evt);
            }
        });

        Producto.setText("Producto");

        jLabel8.setText("Clase de Requerimiento");

        AsesoConsul.setText("Asesoria/Consultoria");

        jLabel7.setText("Plazo publicacion solicitado ");

        StockBodeSi.setText("Si");

        StockBodeNo.setText("No");

        jLabel35.setText("¿Anexo?");

        AnexoSi.setText("Si");

        AnexoNo.setText("No");

        MoDeRe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CM", "TD", "<3UTM" }));

        ProBusOf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CM", "LP", "TD", "<3UTM" }));
        ProBusOf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProBusOfActionPerformed(evt);
            }
        });

        DeptoYUni.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Division Tecnica", "Unidad de Administración y Finanzas", "Unidad de Auditoría Interna", "Unidad de Ingeniería y Desarrollo", "Unidad de Operaciones" }));

        jButton1.setText("Guardar Formulario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Impuesto");

        jLabel14.setText("Valor de todo estimado en pesos");

        jLabel49.setText("Valor estimado (impto. Incl.)");

        jLabel50.setText("$");

        VBAdquisiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VBAdquisicionesActionPerformed(evt);
            }
        });

        jLabel48.setText("V° B° Adquisiciones");

        jLabel44.setText("SUBT.");

        jLabel43.setText("Asig PPTARIA");

        jLabel46.setText("SALDO PPTARIO M$");

        jLabel47.setText("V° B° finanzas");

        jLabel45.setText("ITEM/ASIGNAC.");

        AsigPptariaSubt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsigPptariaSubtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel31))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ProBusOf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MoDeRe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MotivosDelaNecesidadyDestino)
                                    .addComponent(DescipGeneDelProSer, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                                    .addComponent(RecomendaProve)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(583, 583, 583)
                                .addComponent(jLabel35)
                                .addGap(18, 18, 18)
                                .addComponent(AnexoSi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AnexoNo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Fecha1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(14, 14, 14)
                                                        .addComponent(jLabel3))
                                                    .addComponent(FechaRecep, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(24, 24, 24)
                                                        .addComponent(jLabel4))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(HoraRecep, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(24, 24, 24)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5)
                                                    .addComponent(Recibe)))
                                            .addComponent(PeriUso)
                                            .addComponent(Cargo)
                                            .addComponent(Solicitante, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                            .addComponent(DeptoYUni, 0, 0, Short.MAX_VALUE)))
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel20)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(TipoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(DiezDias)
                                            .addComponent(SeisDias)
                                            .addComponent(VeinteDias))
                                        .addGap(21, 21, 21)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(AsesoConsul)
                                            .addComponent(Producto)
                                            .addComponent(TrabajoSer)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel23)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(StockBodeSi)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(StockBodeNo))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Dtecnum, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jToggleButton2)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(56, 56, 56)
                                        .addComponent(jLabel8))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel43)
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AsigPptariaSubt, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel44))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ItemAsignac, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel45, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel46)
                                    .addComponent(Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(VBFinanzas)
                                    .addComponent(jLabel47))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(VBAdquisiciones)
                                        .addGap(71, 71, 71))
                                    .addComponent(jLabel48)))
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ValorTPesos)
                                        .addComponent(Impuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel49))
                                    .addComponent(ValEst, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel50))))
                .addContainerGap(661, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel52)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel10)
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(DeptoYUni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Solicitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PeriUso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Dtecnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(SeisDias)
                                    .addComponent(Producto))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(DiezDias)
                                    .addComponent(TrabajoSer))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel20)
                                            .addComponent(TipoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel23)
                                            .addComponent(StockBodeSi)
                                            .addComponent(StockBodeNo)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(VeinteDias)
                                        .addComponent(AsesoConsul)))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(DescipGeneDelProSer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MotivosDelaNecesidadyDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(MoDeRe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(RecomendaProve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ProBusOf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AnexoSi)
                                    .addComponent(AnexoNo)
                                    .addComponent(jLabel35))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(FechaRecep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(HoraRecep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Recibe))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel45)
                                    .addComponent(jLabel46)
                                    .addComponent(jLabel47)
                                    .addComponent(jLabel48)
                                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel43))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ItemAsignac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(AsigPptariaSubt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(VBAdquisiciones)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(VBFinanzas)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ValorTPesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Impuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel49)
                                .addGap(8, 8, 8)
                                .addComponent(ValEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel50)
                                .addGap(6, 6, 6)))))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void PeriUsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PeriUsoActionPerformed
// TODO add your handling code here:     
}//GEN-LAST:event_PeriUsoActionPerformed

private void Fecha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fecha1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_Fecha1ActionPerformed

private void CargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargoActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_CargoActionPerformed

private void DtecnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DtecnumActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_DtecnumActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
    new GestionMenu().setVisible(true);
    this.setVisible(false);
    
}//GEN-LAST:event_jButton3ActionPerformed

private void DescipGeneDelProSerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescipGeneDelProSerActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_DescipGeneDelProSerActionPerformed

private void RecomendaProveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecomendaProveActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_RecomendaProveActionPerformed

private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
         if(!Dtecnum.getText().equals("")){
        try{
        int Numero= Integer.parseInt(Dtecnum.getText());
        HashMap datos = cl.BuscarFormulario(Numero);          
        if(datos!=null){
        String FechaRecep1=(String)datos.get("FechaRecp1");
        System.out.println("este es el valor de fecha : "+FechaRecep1);
        FechaRecep.setText(FechaRecep1);
       
        String HoraRecep1=(String)datos.get("HoraRecep1");
        HoraRecep.setText(HoraRecep1);
        String Recibe1=(String)datos.get("Recibe");
        if(Recibe1.equals("1")){Recibe.setSelected(true);}else{Recibe.setSelected(false);}
        String Fecha11=(String)datos.get("Fecha"); 
        Fecha1.setText(Fecha11);
        String Deptoyounidad1=(String)datos.get("Deptoyounidad1");
        DeptoYUni.setSelectedItem(Deptoyounidad1);
        String TipoC=(String)datos.get("TC");
        TipoCompra.setSelectedItem(TipoC);
        String ProBF=(String)datos.get("ProcedDeBusqueda1");        
        ProBusOf.setSelectedItem(ProBF);
        String MDR=(String)datos.get("MotivoDeRecom1");
        MoDeRe.setSelectedItem(MDR);
        String Solicitante1=(String)datos.get("Solicitante1");
        Solicitante.setText(Solicitante1);
        String Cargo1=(String)datos.get("Cargo1");
        Cargo.setText(Cargo1);
        String PeriUso1=(String)datos.get("PeriUso1");
        PeriUso.setText(PeriUso1);
        String Plazo1=(String)datos.get("Plazo");
        String Clase1=(String)datos.get("Clase"); 
        String Stockbode1=(String)datos.get("StockBode");
        String Anexo1=(String)datos.get("Anexo"); 
        if(Plazo1.equals("6")){
        SeisDias.setSelected(true);
        }
        if(Plazo1.equals("10")){
        DiezDias.setSelected(true);
        }
        if(Plazo1.equals("20")){
        VeinteDias.setSelected(true);
        }
        if(Clase1.equals("p")){
        Producto.setSelected(true);
        }
        if(Clase1.equals("ts")){
        TrabajoSer.setSelected(true);
        }
        if(Clase1.equals("ac")){
        AsesoConsul.setSelected(true);
        }
        if(Stockbode1.equals("s")){     
        StockBodeSi.setSelected(true);
        }
        if(Stockbode1.equals("n")){
        StockBodeNo.setSelected(true);    
        }
        if(Stockbode1.equals("s")){     
        StockBodeSi.setSelected(true);
        }
        if(Stockbode1.equals("n")){
        StockBodeNo.setSelected(true);    
        }
        if(Anexo1.equals("s")){     
        AnexoSi.setSelected(true);
        }
        if(Anexo1.equals("n")){
        AnexoNo.setSelected(true);    
        }
        String DescipgeneDelProSer1=(String)datos.get("DescipGeneDelProSer1");
        DescipGeneDelProSer.setText(DescipgeneDelProSer1);
        String MotivosDelaNecesidadyDestino1=(String)datos.get("MotivosDelaNecesidadyDestino1");
        MotivosDelaNecesidadyDestino.setText(MotivosDelaNecesidadyDestino1);
        String RecomendaProve1=(String)datos.get("RecomendaProve1");
        RecomendaProve.setText(RecomendaProve1);
        String AsigPptariasubt1=(String)datos.get("AsigPptariaSubt1");
        AsigPptariaSubt.setText(AsigPptariasubt1);
        String ItemAsignac1=(String)datos.get("ItemAsignac1");
        ItemAsignac.setText(ItemAsignac1);
        String Saldo1=(String)datos.get("Saldo1");
        Saldo.setText(Saldo1);
        String vbffinanzas1=(String)datos.get("vbffinanzas");
        if(vbffinanzas1.equals("1")){VBFinanzas.setSelected(true); }else{VBFinanzas.setSelected(false);}
        String vbaadquisiciones1=(String)datos.get("vbaadquisiciones");
        if(vbaadquisiciones1.equals("1")){VBAdquisiciones.setSelected(true); }else{ VBAdquisiciones.setSelected(false);}        
        String ValEst1=(String)datos.get("ValEst1");
        ValorTPesos.setEditable(false);
        ValEst.setText(ValEst1);
        ValEst.setEditable(false);
        String Valtp=(String)datos.get("ValorTPesos");
        ValorTPesos.setText(Valtp);
        String impe=(String)datos.get("Impuesto");
        Impuesto.setText(impe);
        Impuesto.setEditable(false);
        jTable1.setModel(cl.cargarTablaDatoslo(Numero));    
        }else{
        JOptionPane.showMessageDialog(this, "Formulario no existente, vuelva a ingresar el numero", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
        }
            }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Debe ingresar solo numeros en el numero del formulario", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
            }
        
}else{
        JOptionPane.showMessageDialog(this, "Debe ingresar un numero de formulario", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
       
        Dtecnum.setBackground(Color.RED);

}
}//GEN-LAST:event_jToggleButton2ActionPerformed

private void TipoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoCompraActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_TipoCompraActionPerformed

private void ProBusOfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProBusOfActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_ProBusOfActionPerformed

private void SolicitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolicitanteActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_SolicitanteActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here
        boolean ingreso= true;
        String FechaRecp1=  FechaRecep.getText();
        String HoraRecep1= HoraRecep.getText();     
        boolean Recibe1= Recibe.isSelected();
        String Dtecnum1=  Dtecnum.getText();
        String Fecha =Fecha1.getText();
        String Solicitante1 = Solicitante.getText();
        String Cargo1 = Cargo.getText();
        String PeriUso1= PeriUso.getText();
        String Plazo="";
        if(SeisDias.isSelected()){
        Plazo="6";
        }
        if(DiezDias.isSelected()){
        Plazo="10";
        }
        if(VeinteDias.isSelected()){
        Plazo="20";
        }
        
        String Clase="";
        
        if(Producto.isSelected()){
        Clase="p";
        }
        if(TrabajoSer.isSelected()){
        Clase="ts";
        }
        if(AsesoConsul.isSelected()){
        Clase="ac";
        }
       
        String StockBode="";
       if(StockBodeSi.isSelected()){     
       StockBode="s";
       }
       if(StockBodeNo.isSelected()){
       StockBode="n";    
       }
       String DescipGeneDelProSer1=DescipGeneDelProSer.getText();
       String MotivosDelaNecesidadyDestino1=MotivosDelaNecesidadyDestino.getText();
       String RecomendaProve1= RecomendaProve.getText();
       String Anexo="";
       if(AnexoSi.isSelected()){     
       Anexo="s";
       }
       if(AnexoNo.isSelected()){
       Anexo="n";    
       }
        String AsigPptariaSubt1= AsigPptariaSubt.getText();
        String ItemAsignac1=ItemAsignac.getText();
        int Saldo1=0;
        try{
        Saldo1=Integer.parseInt(Saldo.getText());
        }catch(Exception e){
            
        JOptionPane.showMessageDialog(this, "Debe ingresar solo numeros en el saldo", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
        }
        boolean vbffinanzas= VBFinanzas.isSelected(); 
        boolean vbaadquisiciones= VBAdquisiciones.isSelected();   
        Object depu = DeptoYUni.getSelectedItem();
        String DepUni = String.valueOf(depu);
        Object e = TipoCompra.getSelectedItem();
        String TipoC = String.valueOf(e);
        Object eo = MoDeRe.getSelectedItem();
        String MoDeR = String.valueOf(eo);
        Object eoi = ProBusOf.getSelectedItem();
        String ProBusO = String.valueOf(eoi);
        double ValEst1=Double.parseDouble(ValEst.getText());  
        double Vtp= Double.parseDouble(ValorTPesos.getText());
        double Imp= Double.parseDouble(Impuesto.getText());
    if(Saldo1==0){
    JOptionPane.showMessageDialog(this, "Debe ingresar un numero en el saldo", "Advertencia", JOptionPane.OK_CANCEL_OPTION);      
    ingreso= false;
    }
    if(myMap==null){
    JOptionPane.showMessageDialog(this, "Debe ingresar algun producto o servicio a la lista", "Advertencia", JOptionPane.OK_CANCEL_OPTION);      
    ingreso= false;
    } 
    if(FechaRecep.getText().equals("")){
    JOptionPane.showMessageDialog(this, "Debe ingresar la fecha para publicacion en mercadolibre.cl", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
    FechaRecep.setBackground(Color.RED);
    ingreso= false;
    }
    if(HoraRecep.getText().equals("")){
    JOptionPane.showMessageDialog(this, "Debe ingresar la hora para la publicacion en mercadolibre.cl", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
    HoraRecep.setBackground(Color.RED);
    ingreso= false;
    }
    if(Dtecnum.getText().equals("")){
    JOptionPane.showMessageDialog(this, "Debe ingresar el Numero del formulario de requerimiento", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
    Dtecnum.setBackground(Color.RED);
    ingreso= false;
    }
    if(Fecha1.getText().equals("")){
    JOptionPane.showMessageDialog(this, "Debe ingresar la Fecha del formulario", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
    Fecha1.setBackground(Color.RED);
    ingreso= false;
    }  
    if(Solicitante.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Debe ingresar el solicitante", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
        Solicitante.setBackground(Color.RED);
        ingreso= false;
    }
    if(Cargo.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Debe ingresar el Cargo", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
        Cargo.setBackground(Color.RED);
        ingreso= false;
    }
    if(PeriUso.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Debe ingresar el Periodo de uso", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
        PeriUso.setBackground(Color.RED);
        ingreso= false;
    }
    if(DescipGeneDelProSer.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Debe ingresar la descripcion general del producto/servicio", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
        DescipGeneDelProSer.setBackground(Color.RED);
        ingreso= false;
    }
    if(MotivosDelaNecesidadyDestino.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Debe ingresar el motivo de necesidad y destino final del producto y/o servicio", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
        MotivosDelaNecesidadyDestino.setBackground(Color.RED);
        ingreso= false;
    }
    if(RecomendaProve.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Debe ingresar Recomendacion de proveedores", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
        RecomendaProve.setBackground(Color.RED);
        ingreso= false;
    }
    if(AsigPptariaSubt.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Debe ingresar la asignacion Pptaria subt", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
        AsigPptariaSubt.setBackground(Color.RED);
        ingreso= false;
    }
    if(ItemAsignac.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Debe ingresar la asignacion Pptaria Item/ Asignac.", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
        ItemAsignac.setBackground(Color.RED);
        ingreso= false;
    }    
     if(Saldo.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Debe ingresar la persona a cargo de la decision ", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
        Saldo.setBackground(Color.RED);
        ingreso= false;
    }
    if(ingreso){
       boolean resul=cl.Modificar1(FechaRecp1,HoraRecep1,Recibe1,Dtecnum1,Fecha,DepUni,Solicitante1,Cargo1,PeriUso1,Plazo,Clase,TipoC,StockBode,DescipGeneDelProSer1,MotivosDelaNecesidadyDestino1,ProBusO,RecomendaProve1,MoDeR,Anexo,AsigPptariaSubt1,ItemAsignac1,Saldo1,vbffinanzas,vbaadquisiciones,ValEst1,Vtp,Imp);
       //boolean result2=cl.AgregarListaDeDatos(myMap, Dtecnum.getText());     
       Mail m = new Mail("Se ha modificado un formulario de requerimiento. Numero de formulario : "+ Dtecnum.getText()+" Usuario que lo ingresó :"+ Login.nom);
       m.send();// Mandar mensaje de modificacion de archivo  " Se ha ingresado el formulario de requerimiento numero:....por la cuenta con nombre:" 
       if(resul){//&&resul
       JOptionPane.showMessageDialog(this, "Se ha ingresado el formulario junto con su lista de productos de forma exitosa", "Informacion", ICONIFIED);
       }else{
       JOptionPane.showMessageDialog(this, "No se ha logrado ingresar el formulario, revise los campos de datos", "Informacion", JOptionPane.OK_OPTION);
       myMap=null;
       resultado=null;
       valor=0;
       }
    }else{
        JOptionPane.showMessageDialog(this, "No se ha logrado ingresar, revise los campos de datos", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
    
    }   
}//GEN-LAST:event_jButton1ActionPerformed

private void VBAdquisicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VBAdquisicionesActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_VBAdquisicionesActionPerformed

private void AsigPptariaSubtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsigPptariaSubtActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_AsigPptariaSubtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ulti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ulti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ulti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ulti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Modificar1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AnexoNo;
    private javax.swing.JRadioButton AnexoSi;
    private javax.swing.JRadioButton AsesoConsul;
    private javax.swing.JTextField AsigPptariaSubt;
    private javax.swing.JTextField Cargo;
    private javax.swing.JComboBox DeptoYUni;
    private javax.swing.JTextField DescipGeneDelProSer;
    private javax.swing.JRadioButton DiezDias;
    private javax.swing.JTextField Dtecnum;
    private javax.swing.JTextField Fecha1;
    private javax.swing.JTextField FechaRecep;
    private javax.swing.JTextField HoraRecep;
    private javax.swing.JTextField Impuesto;
    private javax.swing.JTextField ItemAsignac;
    private javax.swing.JComboBox MoDeRe;
    private javax.swing.JTextField MotivosDelaNecesidadyDestino;
    private javax.swing.JTextField PeriUso;
    private javax.swing.JComboBox ProBusOf;
    private javax.swing.JRadioButton Producto;
    private javax.swing.JCheckBox Recibe;
    private javax.swing.JTextField RecomendaProve;
    private javax.swing.JTextField Saldo;
    private javax.swing.JRadioButton SeisDias;
    private javax.swing.JTextField Solicitante;
    private javax.swing.JRadioButton StockBodeNo;
    private javax.swing.JRadioButton StockBodeSi;
    private javax.swing.JComboBox TipoCompra;
    private javax.swing.JRadioButton TrabajoSer;
    private javax.swing.JCheckBox VBAdquisiciones;
    private javax.swing.JCheckBox VBFinanzas;
    private javax.swing.JTextField ValEst;
    private javax.swing.JTextField ValorTPesos;
    private javax.swing.JRadioButton VeinteDias;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
