/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ulti.java
 *
 * Created on 16-jun-2013, 23:40:34
 */
package formularioderequerimientodeproductoservicio;

import Logica.ControladorLogica;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.ScrollPane;
import java.util.Date;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Walter
 */
public class ultiDesp extends javax.swing.JFrame {
 private ControladorLogica cl;
    //private static ArrayList <HashMap>;
    private static DefaultTableModel ingresoDatos;
    private static String[] resultado= new String[7];
    private static String[] nombreTabla= {"Dtecnum1","Descripcion En detalle del Requerimiento","Producto/Servicio","Cantidad","Precio Estimado Unitario Neto","Valor Estimado Total por Item Neto","Valor total Pesos"};
    private static int valor=1;
    
private static final long serialVersionUID = 1L;
private ScrollPane elSP;
   
    /** Creates new form ulti */
    public ultiDesp() {
       initComponents();
       PanelFondo F= new PanelFondo();
       this.add(F,BorderLayout.CENTER);
       this.pack();
       cl= new ControladorLogica();     
       //setSize(2000, 900);
       //elSP = new ScrollPane(ScrollPane.
       //SCROLLBARS_ALWAYS);
       //elSP.add(this);
       //elSP.setVisible(true);
       //add(elSP);
       jLabel15.setText("Usuario en el sistema : "+Login.nom);
       ingresoDatos = new DefaultTableModel(null, nombreTabla);
       buttonGroup1.add(SeisDias);
       buttonGroup1.add(DiezDias);
       buttonGroup1.add(VeinteDias); 
       buttonGroup2.add(Producto);
       buttonGroup2.add(TrabajoSer);
       buttonGroup2.add(AsesoConsul);
       buttonGroup3.add(StockBodeSi);
       buttonGroup3.add(StockBodeNo);
       buttonGroup4.add(AnexoSi);
       buttonGroup4.add(AnexoNo);
    }

  
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PeriUso = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Fecha1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Cargo = new javax.swing.JTextField();
        Solicitante = new javax.swing.JTextField();
        Recibe = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        HoraRecep = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        FechaRecep = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        Dtecnum = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        DescipGeneDelProSer = new javax.swing.JTextField();
        MotivosDelaNecesidadyDestino = new javax.swing.JTextField();
        RecomendaProve = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        ItemAsignac = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        Saldo = new javax.swing.JTextField();
        AsigPptariaSubt = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ValEst = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        VBFinanzas = new javax.swing.JCheckBox();
        VBAdquisiciones = new javax.swing.JCheckBox();
        jLabel50 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        ProBusOf = new javax.swing.JComboBox();
        MoDeRe = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        DiezDias = new javax.swing.JRadioButton();
        SeisDias = new javax.swing.JRadioButton();
        TrabajoSer = new javax.swing.JRadioButton();
        VeinteDias = new javax.swing.JRadioButton();
        TipoCompra = new javax.swing.JComboBox();
        Producto = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        AsesoConsul = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        StockBodeSi = new javax.swing.JRadioButton();
        StockBodeNo = new javax.swing.JRadioButton();
        jLabel35 = new javax.swing.JLabel();
        AnexoSi = new javax.swing.JRadioButton();
        AnexoNo = new javax.swing.JRadioButton();
        DeptoYUni = new javax.swing.JComboBox();
        Impuesto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ValorTPesos = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jCalendarCombo1 = new org.freixas.jcalendar.JCalendarCombo();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setText(" 2013  N° de formulario :");

        jLabel2.setText("Fechar recepcion para publicacion en marcadopublico.cl ");

        jLabel9.setText("Fecha");

        jLabel5.setText("Recibe");

        PeriUso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PeriUsoActionPerformed(evt);
            }
        });

        jLabel11.setText("Solicitante");

        Fecha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fecha1ActionPerformed(evt);
            }
        });

        jLabel12.setText("Cargo");

        jLabel10.setText("Depto. y/o Unidad");

        jLabel13.setText("Periodo de Uso");

        Cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargoActionPerformed(evt);
            }
        });

        jLabel3.setText("Fecha ");

        jLabel4.setText("Hora");

        jButton3.setText("Volver");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Dtecnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DtecnumActionPerformed(evt);
            }
        });

        jLabel52.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel52.setText("Despliegue de Formulario De Requerimiento De Producto y/o Servicios");

        jLabel31.setText("Motivo de recomendacion ( CM,TD,<3UTM)");

        DescipGeneDelProSer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescipGeneDelProSerActionPerformed(evt);
            }
        });

        RecomendaProve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecomendaProveActionPerformed(evt);
            }
        });

        jLabel26.setText("Descripcion general de Producto / Servicio");

        jLabel29.setText("Procedimientos de busqueda oferentes  (CM,LP,TD,<3UTM)");

        jLabel27.setText("Motivos de la necesidad y destino final del producto y/o servicio");

        jLabel30.setText("Recomendacion de proveedores");

        jLabel43.setText("Asig PPTARIA");

        jLabel44.setText("SUBT.");

        AsigPptariaSubt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsigPptariaSubtActionPerformed(evt);
            }
        });

        jLabel46.setText("SALDO PPTARIO M$");

        jLabel47.setText("V° B° finanzas");

        jLabel45.setText("ITEM/ASIGNAC.");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel48.setText("V° B° Adquisiciones");

        VBAdquisiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VBAdquisicionesActionPerformed(evt);
            }
        });

        jLabel50.setText("$");

        jLabel49.setText("Valor estimado (impto. Incl.)");

        jToggleButton2.setText("Busqueda y despliegue");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        ProBusOf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CM", "LP", "TD", "<3UTM" }));
        ProBusOf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProBusOfActionPerformed(evt);
            }
        });

        MoDeRe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CM", "TD", "<3UTM" }));

        jLabel23.setText("Stock en Bodega");

        jLabel20.setText("Tipo De Compra");

        DiezDias.setText("+10 dias >100<1000 utm ");

        SeisDias.setText(" +6 dias < 100 utm");

        TrabajoSer.setText("Trabajo/Servicio");

        VeinteDias.setText("+20 dias > 1000 utm");

        TipoCompra.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rutinaria", "Estrategica" }));
        TipoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoCompraActionPerformed(evt);
            }
        });

        Producto.setText("Producto");

        jLabel8.setText("Clase de Requerimiento");

        AsesoConsul.setText("Asesoria/Consultoria");

        jLabel7.setText("Plazo publicacion solicitado ");

        StockBodeSi.setText("Si");

        StockBodeNo.setText("No");

        jLabel35.setText("¿Anexo?");

        AnexoSi.setText("Si");

        AnexoNo.setText("No");

        DeptoYUni.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Division Tecnica", "Unidad de Administración y Finanzas", "Unidad de Auditoría Interna", "Unidad de Ingeniería y Desarrollo", "Unidad de Operaciones" }));

        jLabel1.setText("Impuesto");

        jLabel14.setText("Valor de todo estimado en pesos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCalendarCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FechaRecep, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HoraRecep, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(Recibe)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Solicitante, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Cargo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                .addComponent(PeriUso, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(DeptoYUni, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                                .addComponent(Fecha1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(DiezDias)
                                    .addComponent(SeisDias)
                                    .addComponent(VeinteDias)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TipoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(TrabajoSer)
                                    .addComponent(Producto)
                                    .addComponent(AsesoConsul)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(StockBodeSi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(StockBodeNo))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jToggleButton2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Dtecnum, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(29, 29, 29)))
                        .addGap(136, 136, 136))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel30))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(MoDeRe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MotivosDelaNecesidadyDestino)
                                    .addComponent(DescipGeneDelProSer, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                                    .addComponent(ProBusOf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RecomendaProve))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                .addComponent(jLabel35)
                                .addGap(18, 18, 18)
                                .addComponent(AnexoSi))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(AnexoNo))
                        .addGap(64, 64, 64))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel43)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel44, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AsigPptariaSubt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ItemAsignac, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel45, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel46)
                    .addComponent(Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VBFinanzas)
                    .addComponent(jLabel47))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VBAdquisiciones)
                    .addComponent(jLabel48))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel50)
                        .addGap(18, 18, 18)
                        .addComponent(ValEst, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel49))
                .addContainerGap(168, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(623, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ValorTPesos)
                        .addComponent(Impuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(125, 125, 125))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52)
                    .addComponent(jButton3)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jToggleButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jCalendarCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(FechaRecep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(HoraRecep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Recibe))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(Fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(DeptoYUni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Solicitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel13))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PeriUso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Dtecnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Producto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TrabajoSer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AsesoConsul))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(DiezDias))
                                    .addComponent(SeisDias))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(VeinteDias)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(TipoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23)
                                    .addComponent(StockBodeSi)
                                    .addComponent(StockBodeNo))))))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DescipGeneDelProSer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MotivosDelaNecesidadyDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel29)
                            .addComponent(ProBusOf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(RecomendaProve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MoDeRe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AnexoSi)
                            .addComponent(AnexoNo)
                            .addComponent(jLabel35))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ValorTPesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Impuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel45)
                                .addComponent(jLabel46)
                                .addComponent(jLabel47)
                                .addComponent(jLabel48)
                                .addComponent(jLabel49)
                                .addComponent(jLabel44)
                                .addComponent(jLabel43))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ItemAsignac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AsigPptariaSubt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(VBAdquisiciones)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(VBFinanzas)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel50)
                            .addComponent(ValEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void PeriUsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PeriUsoActionPerformed
// TODO add your handling code here:     
}//GEN-LAST:event_PeriUsoActionPerformed

private void Fecha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fecha1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_Fecha1ActionPerformed

private void CargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargoActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_CargoActionPerformed

private void DtecnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DtecnumActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_DtecnumActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
    new GestionMenu().setVisible(true);
    this.setVisible(false);
    
}//GEN-LAST:event_jButton3ActionPerformed

private void DescipGeneDelProSerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescipGeneDelProSerActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_DescipGeneDelProSerActionPerformed

private void RecomendaProveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecomendaProveActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_RecomendaProveActionPerformed

private void VBAdquisicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VBAdquisicionesActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_VBAdquisicionesActionPerformed
private void AsigPptariaSubtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsigPptariaSubtActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_AsigPptariaSubtActionPerformed
private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:  
        if(!Dtecnum.getText().equals("")){
        try{
        int Numero= Integer.parseInt(Dtecnum.getText());
        HashMap datos = cl.BuscarFormulario(Numero);          
        if(datos!=null){
        String FechaRecep1=(String)datos.get("FechaRecp1");
        System.out.println("este es el valor de fecha : "+FechaRecep1);
                String foo= String.valueOf(jCalendarCombo1.getModel());

       // String FechaRecp1=String.valueOf(jCalendarCombo1.getDate());
        Date d= new Date(FechaRecep1);
        jCalendarCombo1.setDate(d);
        System.out.println(" que volars !!!"+FechaRecep1);
        FechaRecep.setText(FechaRecep1);
        FechaRecep.setEditable(false);
        String HoraRecep1=(String)datos.get("HoraRecep1");
        HoraRecep.setText(HoraRecep1);
        HoraRecep.setEditable(false);
        String Recibe1=(String)datos.get("Recibe");
        if(Recibe1.equals("1")){Recibe.setSelected(true);}else{Recibe.setSelected(false);}
        String Fecha11=(String)datos.get("Fecha"); 
        Fecha1.setText(Fecha11);
        Fecha1.setEditable(false);
        String Deptoyounidad1=(String)datos.get("Deptoyounidad1");
        DeptoYUni.setSelectedItem(Deptoyounidad1);
        DeptoYUni.setEnabled(false);
        String TipoC=(String)datos.get("TC");
        TipoCompra.setSelectedItem(TipoC);
        TipoCompra.setEditable(false);
        String ProBF=(String)datos.get("ProcedDeBusqueda1");        
        ProBusOf.setSelectedItem(ProBF);
        ProBusOf.setEditable(false);
        String MDR=(String)datos.get("MotivoDeRecom1");
        MoDeRe.setSelectedItem(MDR);
        MoDeRe.setEditable(false);
        String Solicitante1=(String)datos.get("Solicitante1");
        Solicitante.setText(Solicitante1);
        Solicitante.setEditable(false);
        String Cargo1=(String)datos.get("Cargo1");
        Cargo.setText(Cargo1);
        Cargo.setEditable(false);
        String PeriUso1=(String)datos.get("PeriUso1");
        PeriUso.setText(PeriUso1);
        PeriUso.setEditable(false);        
        String Plazo1=(String)datos.get("Plazo");
        String Clase1=(String)datos.get("Clase"); 
        String Stockbode1=(String)datos.get("StockBode");
        String Anexo1=(String)datos.get("Anexo"); 
        if(Plazo1.equals("6")){
        SeisDias.setSelected(true);
        }
        if(Plazo1.equals("10")){
        DiezDias.setSelected(true);
        }
        if(Plazo1.equals("20")){
        VeinteDias.setSelected(true);
        }
        if(Clase1.equals("p")){
        Producto.setSelected(true);
        }
        if(Clase1.equals("ts")){
        TrabajoSer.setSelected(true);
        }
        if(Clase1.equals("ac")){
        AsesoConsul.setSelected(true);
        }
        if(Stockbode1.equals("s")){     
        StockBodeSi.setSelected(true);
        }
        if(Stockbode1.equals("n")){
        StockBodeNo.setSelected(true);    
        }
        if(Stockbode1.equals("s")){     
        StockBodeSi.setSelected(true);
        }
        if(Stockbode1.equals("n")){
        StockBodeNo.setSelected(true);    
        }
        if(Anexo1.equals("s")){     
        AnexoSi.setSelected(true);
        }
        if(Anexo1.equals("n")){
        AnexoNo.setSelected(true);    
        }
        String DescipgeneDelProSer1=(String)datos.get("DescipGeneDelProSer1");
        DescipGeneDelProSer.setText(DescipgeneDelProSer1);
        DescipGeneDelProSer.setEditable(false);
        String MotivosDelaNecesidadyDestino1=(String)datos.get("MotivosDelaNecesidadyDestino1");
        MotivosDelaNecesidadyDestino.setText(MotivosDelaNecesidadyDestino1);
        MotivosDelaNecesidadyDestino.setEditable(false);
        String RecomendaProve1=(String)datos.get("RecomendaProve1");
        RecomendaProve.setText(RecomendaProve1);
        RecomendaProve.setEditable(false);
        String AsigPptariasubt1=(String)datos.get("AsigPptariaSubt1");
        AsigPptariaSubt.setText(AsigPptariasubt1);
        AsigPptariaSubt.setEditable(false);
        String ItemAsignac1=(String)datos.get("ItemAsignac1");
        ItemAsignac.setText(ItemAsignac1);
        ItemAsignac.setEditable(false);
        String Saldo1=(String)datos.get("Saldo1");
        Saldo.setText(Saldo1);
        Saldo.setEditable(false);
        String vbffinanzas1=(String)datos.get("vbffinanzas");
        if(vbffinanzas1.equals("1")){VBFinanzas.setSelected(true); }else{VBFinanzas.setSelected(false);}
        String vbaadquisiciones1=(String)datos.get("vbaadquisiciones");
        if(vbaadquisiciones1.equals("1")){VBAdquisiciones.setSelected(true); }else{ VBAdquisiciones.setSelected(false);}        
        String ValEst1=(String)datos.get("ValEst1");
        ValEst.setText(ValEst1);
        ValEst.setEditable(false);
        String Valtp=(String)datos.get("ValorTPesos");
        ValorTPesos.setText(Valtp);
        String impe=(String)datos.get("Impuesto");
        Impuesto.setText(impe);
        jTable1.setModel(cl.cargarTablaDatoslo(Numero));    
        }else{
        JOptionPane.showMessageDialog(this, "Formulario no existente, vuelva a ingresar el numero", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
        }
            }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Debe ingresar solo numeros en el numero del formulario", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
            }
        
}else{
        JOptionPane.showMessageDialog(this, "Debe ingresar un numero de formulario", "Advertencia", JOptionPane.OK_CANCEL_OPTION);
       
        Dtecnum.setBackground(Color.RED);

}
}//GEN-LAST:event_jToggleButton2ActionPerformed

private void TipoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoCompraActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_TipoCompraActionPerformed

private void ProBusOfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProBusOfActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_ProBusOfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ulti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ulti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ulti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ulti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ultiDesp().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AnexoNo;
    private javax.swing.JRadioButton AnexoSi;
    private javax.swing.JRadioButton AsesoConsul;
    private javax.swing.JTextField AsigPptariaSubt;
    private javax.swing.JTextField Cargo;
    private javax.swing.JComboBox DeptoYUni;
    private javax.swing.JTextField DescipGeneDelProSer;
    private javax.swing.JRadioButton DiezDias;
    private javax.swing.JTextField Dtecnum;
    private javax.swing.JTextField Fecha1;
    private javax.swing.JTextField FechaRecep;
    private javax.swing.JTextField HoraRecep;
    private javax.swing.JTextField Impuesto;
    private javax.swing.JTextField ItemAsignac;
    private javax.swing.JComboBox MoDeRe;
    private javax.swing.JTextField MotivosDelaNecesidadyDestino;
    private javax.swing.JTextField PeriUso;
    private javax.swing.JComboBox ProBusOf;
    private javax.swing.JRadioButton Producto;
    private javax.swing.JCheckBox Recibe;
    private javax.swing.JTextField RecomendaProve;
    private javax.swing.JTextField Saldo;
    private javax.swing.JRadioButton SeisDias;
    private javax.swing.JTextField Solicitante;
    private javax.swing.JRadioButton StockBodeNo;
    private javax.swing.JRadioButton StockBodeSi;
    private javax.swing.JComboBox TipoCompra;
    private javax.swing.JRadioButton TrabajoSer;
    private javax.swing.JCheckBox VBAdquisiciones;
    private javax.swing.JCheckBox VBFinanzas;
    private javax.swing.JTextField ValEst;
    private javax.swing.JTextField ValorTPesos;
    private javax.swing.JRadioButton VeinteDias;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton3;
    private org.freixas.jcalendar.JCalendarCombo jCalendarCombo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
